# backbone
numGroups: 8
growthRate: 32
numBlocks: [6, 6, 6, 6]

# transformer
hiddenDims: 512
numHead: 8
numEncoderLayer: 6
numDecoderLayer: 6
dimFeedForward: 2048
dropout: 0.1
numQuery: 100 # 30
numClass: 90 #90

# dataset
targetHeight: 32 # 608
targetWidth: 32 # 608

# training config
lr: 0.00001
lrBackbone: 0.00001
batchSize: 2
weightDecay: 0.0001
epochs: 200
lrDrop: 1000
clipMaxNorm: 0.1

# loss
classCost: 1.0
bboxCost: 5.0
giouCost: 2.0
eosCost: 0.1

# miscellaneous
device: "cuda"
project: "runs/train"
outputDir: "checkpoint"
weightDir: "checkpoint/tiny_coco.pt"
datasetType: "tiny_coco"
taskName: "coco"
numWorkers: 4
multi: False
amp: True